### Сохранить конфиг промпта
POST http://localhost:8000/api/v1/config
Content-Type: application/json

{
  "model": "gpt-4o",
  "prompt_data" : {
    "task": "O‘zbekiston (B-LOC) Respublikasi (E-LOC) Prezidentining (S-PER) 2023 (O) yil (O) 25 (O) yanvardagi (O) Respublika (S-LOC) ijro (O) etuvchi (O) hokimiyat (B-ORG) organlari (E-ORG) faoliyatini (O) samarali (O) yo‘lga (O) qo‘yishga (O) doir (O) birinchi (O) navbatdagi (O) tashkiliy (O) chora (O) tadbirlar (O) to‘g‘risida (O) gi (O) PF (O) 14 (O) son (O) ijrosini (O) ta’minlash (O) maqsadida (O) Oliy (B-ORG) ta’lim (I-ORG) fan (I-ORG) va (I-ORG) innovatsiyalar (I-ORG) vazirligi (E-ORG) faoliyatining (O) ustuvor (O) yo‘nalishlari (O) muvofiq (O) tasdiqlansin (O)",
    "source_language": {
          "name" : "Узбекский Язык",
          "code" : "uz"
    },
    "target_data": [
      {
        "language": {
          "name" : "Русский Язык",
          "code" : "ru"
        },
        "role": "Вы - эксперт по переводу с узбекского на русский с сохранением разметки именованных сущностей BIOES. После каждого слова или предлога в скобках должен быть соответствующий BIOES тэг, к тэгу не должно прилегать никаких знаков препинания. Формат выходных данных строго 'слово (тэг) ...', то есть после каждого пробела после слова идет тэг, а после тэга - слово",
        "answer": "Утвердить (O) приоритетные (O) направления (O) деятельности (O) Министерства (B-ORG) высшего (I-ORG) образования (I-ORG) науки (I-ORG) и (I-ORG) инноваций (E-ORG) в (O) соответствии (O) с (O) Указом (O) Президента (S-PER) Республики (B-LOC) Узбекистан (E-LOC) от (O) 25 (O) января (O) 2023 (O) года (O) № (O) 14 (O) О (O) первоочередных (O) организационных (O) мерах (O) по (O) эффективному (O) функционированию (O) органов (O) исполнительной (O) власти (S-ORG) республики (O)"
      },
      {
        "language": {
          "name" : "Английский Язык",
          "code" : "en"
        },
        "role": "Вы — эксперт по переводу с узбекского на английский язык с сохранением BIOES-разметки именованных сущностей. После каждого слова или предлога в скобках должен быть соответствующий BIOES тэг, к тэгу не должно прилегать никаких знаков препинания. Формат выходных данных строго 'слово (тэг) ...', то есть после каждого пробела после слова идет тэг, а после тэга - слово",
        "answer": "Let (O) the (O) priority (O) directions (O) of (O) the (O) Ministry (B-ORG) of (I-ORG) Higher (I-ORG) Education (I-ORG) Science (I-ORG) and (I-ORG) Innovations (E-ORG) be (O) approved (O) in (O) accordance (O) with (O) the (O) Decree (O) of (O) the (O) President (S-PER) of (O) the (O) Republic (B-LOC) of (I-LOC) Uzbekistan (E-LOC) No. (O) PF-14 (O) dated (O) January (O) 25 (O) 2023 (O) on (O) primary (O) organizational (O) measures (O) to (O) ensure (O) effective (O) operation (O) of (O) the (O) executive (B-ORG) authorities (E-ORG) of (O) the (O) Republic (S-LOC)"
      },
      {
        "language": {
          "name" : "Казахский Язык",
          "code" : "kk"
        },
        "role": "Вы — эксперт по переводу с узбекского на казахский язык с сохранением BIOES-разметки именованных сущностей. После каждого слова или предлога в скобках должен быть соответствующий BIOES тэг, к тэгу не должно прилегать никаких знаков препинания. Формат выходных данных строго 'слово (тэг) ...', то есть после каждого пробела после слова идет тэг, а после тэга - слово",
        "answer": "Бекітілсін (O) Жоғары (B-ORG) білім (I-ORG) ғылым (I-ORG) және (I-ORG) инновациялар (E-ORG) министрлігінің (O) басым (O) бағыттары (O) Республикасы (B-LOC) Өзбекстанның (E-LOC) Президентінің (S-PER) 2023 (O) жылдың (O) 25 (O) қаңтарындағы (O) № (O) 14 (O) ПФ (O) Жарлығына (O) сәйкес (O) Республикалық (S-LOC) атқарушы (O) билік (B-ORG) органдарының (E-ORG) тиімді (O) жұмыс (O) істеуін (O) қамтамасыз (O) етуге (O) байланысты (O) бірінші (O) кезектегі (O) ұйымдастырушылық (O) шаралар (O) туралы (O)"
      }
    ]
  }
}

### Получить текущий конфиг промпта
GET http://localhost:8000/api/v1/config